#include "Combat/Noise/Private/BtlEnm010.h"

// The overlay's data is its own translation unit.
//
// Two facts force this split, both measured rather than assumed:
//  - The reference codegen loads every table through pointers (`ldr r0, =table; ldr r1, [r0]`).
//    With the definitions visible to the code, MWCC's `-ipa file` folds those reads into
//    immediates and silently changes the generated code (`func_ov011_02129188` alone loses
//    40 bytes of match), and even without `-ipa` the visible array sizes perturb register
//    allocation.  The data therefore must not share a translation unit with the functions
//    that read it.
//  - MWCC emits data objects size-sorted, not in definition order, so the *link* order is
//    not expressible from C for arbitrary layouts.  That is a toolchain limitation; the
//    data matches by content (objdiff: .rodata/.data 100%), and the byte image below is
//    verbatim from the delink reference object -- verify with build/scratch/datadiff.py.

// The task entry points the `TaskHandle`s and function tables point at.
extern void func_ov011_021259d0();
extern void func_ov011_02125cf8();
extern void func_ov011_021278d4();
extern void func_ov011_0212791c();
extern void func_ov011_02127a64();
extern void func_ov011_02127b98();
extern void func_ov011_02127bdc();
extern void func_ov011_02127ce0();
extern void func_ov011_0212801c();
extern void func_ov011_02128348();
extern void func_ov011_02128758();
extern void func_ov011_02129934();
extern void func_ov011_0212b99c();
extern void func_ov011_0212b9e4();
extern void func_ov011_0212bac8();
extern void func_ov011_0212bc84();
extern void func_ov011_0212bcc8();

// MARK: Data -- the original .rodata/.data/.bss byte image, symbols in address
// order.  Generated by build/scratch/datagen.py from the delink reference object;
// verify with build/scratch/datadiff.py.  .rodata symbols are const and .data
// symbols are not: the string blob lives in .data in the original.

// Word-shape records for the pointer-bearing tables.
typedef struct Ov011Rec_WP {
    u32   w0;
    void* w1;
} Ov011Rec_WP;
typedef struct Ov011Rec_PPWW {
    void* w0;
    void* w1;
    u32   w2;
    u32   w3;
} Ov011Rec_PPWW;
typedef struct Ov011Rec_WPWPWP {
    u32   w0;
    void* w1;
    u32   w2;
    void* w3;
    u32   w4;
    void* w5;
} Ov011Rec_WPWPWP;
typedef struct Ov011Rec_WPWPW {
    u32   w0;
    void* w1;
    u32   w2;
    void* w3;
    u32   w4;
} Ov011Rec_WPWPW;
typedef struct Ov011Rec_P {
    void* w0;
} Ov011Rec_P;
typedef struct Ov011Rec_PPW {
    void* w0;
    void* w1;
    u32   w2;
} Ov011Rec_PPW;
typedef struct Ov011Rec_PPPP {
    void* w0;
    void* w1;
    void* w2;
    void* w3;
} Ov011Rec_PPPP;
typedef struct Ov011Rec_PPPPPPPPPPPPPPPPPPPPP {
    void* w0;
    void* w1;
    void* w2;
    void* w3;
    void* w4;
    void* w5;
    void* w6;
    void* w7;
    void* w8;
    void* w9;
    void* w10;
    void* w11;
    void* w12;
    void* w13;
    void* w14;
    void* w15;
    void* w16;
    void* w17;
    void* w18;
    void* w19;
    void* w20;
} Ov011Rec_PPPPPPPPPPPPPPPPPPPPP;

// Forward declarations: MWCC rejects forward references in static
// initializers, and the records below point at later symbols.
extern const Ov011Rec_WP              data_ov011_0212bdd8;
extern const u8                       data_ov011_0212bde0[];
extern const Ov011Rec_PPWW            data_ov011_0212bde8;
extern const Ov011Rec_PPWW            data_ov011_0212bdf8;
extern const Ov011Rec_PPWW            data_ov011_0212be08;
extern const Ov011Rec_PPWW            data_ov011_0212be18;
extern const Ov011Rec_WPWPWP          data_ov011_0212be28;
extern const Ov011Rec_WP              data_ov011_0212be40;
extern const Ov011Rec_WP              data_ov011_0212be48;
extern const Ov011Rec_WP              data_ov011_0212be50;
extern const Ov011Rec_WPWPWP          data_ov011_0212be58;
extern const Ov011Rec_WP              data_ov011_0212be70;
extern const Ov011Rec_WPWPWP          data_ov011_0212be78;
extern const Ov011Rec_WP              data_ov011_0212be90;
extern const Ov011Rec_WPWPWP          data_ov011_0212be98;
extern const Ov011Rec_WP              data_ov011_0212beb0;
extern const Ov011Rec_WPWPWP          data_ov011_0212beb8;
extern const Ov011Rec_WP              data_ov011_0212bed0;
extern const Ov011Rec_WPWPWP          data_ov011_0212bed8;
extern const Ov011Rec_WP              data_ov011_0212bef0;
extern const Ov011Rec_WPWPWP          data_ov011_0212bef8;
extern const Ov011Rec_WP              data_ov011_0212bf10;
extern const Ov011Rec_WPWPW           data_ov011_0212bf18;
extern const Ov011Rec_P               data_ov011_0212bf2c;
extern const Ov011Rec_WP              data_ov011_0212bf30;
extern const Ov011Rec_WPWPWP          data_ov011_0212bf38;
extern const Ov011Rec_WP              data_ov011_0212bf50;
extern const Ov011Rec_WPWPWP          data_ov011_0212bf58;
extern const Ov011Rec_WP              data_ov011_0212bf70;
extern const u16                      data_ov011_0212bf78[];
extern const u16                      data_ov011_0212bf7e[];
extern const u8                       data_ov011_0212bf84[];
extern const u8                       data_ov011_0212bf8c[];
extern const u8                       data_ov011_0212bf94[];
extern const u8                       data_ov011_0212bf9c[];
extern const TaskHandle               data_ov011_0212bfa4;
extern const u8                       data_ov011_0212bfb0[];
extern const u8                       data_ov011_0212bfc0[];
extern const u8                       data_ov011_0212bfd0[];
extern const u16                      data_ov011_0212bfe0[];
extern const u16                      data_ov011_0212bff4[];
extern const u8                       data_ov011_0212c008[];
extern const u8                       data_ov011_0212c020[];
extern const u8                       data_ov011_0212c040[];
extern const u8                       data_ov011_0212c060[];
extern const u8                       data_ov011_0212c090[];
extern const u8                       data_ov011_0212c0c0[];
extern const TaskHandle               data_ov011_0212c118;
extern const s32                      data_ov011_0212c124[];
extern const Ov011Rec_PPW             data_ov011_0212c130;
extern const BtlEnm010RGAim           data_ov011_0212c13c[];
extern const s32                      data_ov011_0212c148[];
extern const BtlEnm010RGEntry         data_ov011_0212c158;
extern const s32                      data_ov011_0212c168[];
extern const s32                      data_ov011_0212c178[];
extern const s32                      data_ov011_0212c18c[];
extern const s32                      data_ov011_0212c1a0[];
extern const s32                      data_ov011_0212c1b8[];
extern const TaskHandle               data_ov011_0212c1d4;
extern const TaskHandle               data_ov011_0212c1e0;
extern const s32                      data_ov011_0212c1ec[];
extern const TaskHandle               data_ov011_0212c1f8;
extern const s32                      data_ov011_0212c204[];
extern const TaskHandle               data_ov011_0212c210;
extern const s32                      data_ov011_0212c21c[];
extern const s32                      data_ov011_0212c230[];
extern const TaskHandle               data_ov011_0212c240;
extern const s32                      data_ov011_0212c24c[];
extern const s32                      data_ov011_0212c25c[];
extern const s32                      data_ov011_0212c274[];
extern const u16                      data_ov011_0212c28c[];
extern const u16                      data_ov011_0212c28e[];
extern const u16                      data_ov011_0212c290[];
extern const s16                      data_ov011_0212c30c[];
extern const s16                      data_ov011_0212c30e[];
extern const char                     data_ov011_0212c310[8];
extern const char                     data_ov011_0212c318[8];
extern const char                     data_ov011_0212c320[8];
extern const char                     data_ov011_0212c328[8];
extern const s32                      data_ov011_0212c330[];
extern const s32                      data_ov011_0212c33c[];
extern const s32                      data_ov011_0212c34c[];
extern const s32                      data_ov011_0212c35c[];
extern const BtlEnm010FnTable         data_ov011_0212c36c;
extern const s32                      data_ov011_0212c37c[];
extern const s32                      data_ov011_0212c390[];
extern const s32                      data_ov011_0212c3a8[];
extern const s32                      data_ov011_0212c3c8[];
extern const u16                      data_ov011_0212c3cc[];
extern const s32                      data_ov011_0212c3d0[];
extern const s16                      data_ov011_0212c3d4[];
extern const Ov011Rec_PPW             data_ov011_0212c448;
extern Ov011Rec_PPPP                  data_ov011_0212c460;
extern char                           data_ov011_0212c470[36];
extern char                           data_ov011_0212c494[36];
extern char                           data_ov011_0212c4b8[36];
extern char                           data_ov011_0212c4dc[36];
extern char                           data_ov011_0212c500[36];
extern u8                             data_ov011_0212c524[];
extern char                           data_ov011_0212c534[20];
extern char                           data_ov011_0212c548[36];
extern char                           data_ov011_0212c56c[36];
extern char                           data_ov011_0212c590[36];
extern char                           data_ov011_0212c5b4[36];
extern char                           data_ov011_0212c5d8[36];
extern char                           data_ov011_0212c5fc[36];
extern char                           data_ov011_0212c620[];
extern char                           data_ov011_0212c644[];
extern char                           data_ov011_0212c668[];
extern char                           data_ov011_0212c68c[];
extern char                           data_ov011_0212c6b0[];
extern char                           data_ov011_0212c6d4[];
extern char                           data_ov011_0212c6f8[];
extern char                           data_ov011_0212c71c[];
extern char                           data_ov011_0212c740[];
extern char                           data_ov011_0212c764[];
extern char                           data_ov011_0212c788[40];
extern char                           data_ov011_0212c7b0[40];
extern char                           data_ov011_0212c7d8[40];
extern char                           data_ov011_0212c800[40];
extern char                           data_ov011_0212c828[40];
extern char                           data_ov011_0212c850[40];
extern char                           data_ov011_0212c878[40];
extern char                           data_ov011_0212c8a0[40];
extern char                           data_ov011_0212c8c8[40];
extern char                           data_ov011_0212c8f0[40];
extern char                           data_ov011_0212c918[40];
extern char                           data_ov011_0212c940[40];
extern char                           data_ov011_0212c968[40];
extern char                           data_ov011_0212c990[40];
extern char                           data_ov011_0212c9b8[40];
extern char                           data_ov011_0212c9e0[40];
extern char                           data_ov011_0212ca08[40];
extern char                           data_ov011_0212ca30[];
extern char                           data_ov011_0212ca58[44];
extern char                           data_ov011_0212ca84[44];
extern char                           data_ov011_0212cab0[44];
extern const void*                    data_ov011_0212cadc[];
extern const void*                    data_ov011_0212cae8[];
extern const void*                    data_ov011_0212caf4[];
extern const void*                    data_ov011_0212cb1c[];
extern Ov011Rec_PPPPPPPPPPPPPPPPPPPPP data_ov011_0212cb68;
extern char                           data_ov011_0212cbbc[24];
extern char                           data_ov011_0212cbd4[20];
extern char                           data_ov011_0212cbe8[20];
extern char                           data_ov011_0212cbfc[20];
extern char                           data_ov011_0212cc10[20];
extern char                           data_ov011_0212cc24[20];
extern char                           data_ov011_0212cc38[28];
extern char                           data_ov011_0212cc54[20];
extern char                           data_ov011_0212cc68[20];
extern const void*                    data_ov011_0212cc7c[];
extern char                           data_ov011_0212cc8c[20];

const Ov011Rec_WP data_ov011_0212bdd8 = {0x00000003, data_ov011_0212c548};

const u8 data_ov011_0212bde0[8] = {1, 0, 3, 0, 2, 0, 0, 0};

const Ov011Rec_PPWW data_ov011_0212bde8 = {&data_ov011_0212be28, data_ov011_0212bde0, 0x00080000, 0x00000180};

const Ov011Rec_PPWW data_ov011_0212bdf8 = {&data_ov011_0212be28, data_ov011_0212bde0, 0x00070000, 0x00000180};

const Ov011Rec_PPWW data_ov011_0212be08 = {&data_ov011_0212be40, data_ov011_0212bde0, 0x00070000, 0x00000180};

const Ov011Rec_PPWW data_ov011_0212be18 = {&data_ov011_0212be28, data_ov011_0212bde0, 0x00090000, 0x00000180};

const Ov011Rec_WPWPWP data_ov011_0212be28 = {0x00000003,          data_ov011_0212ca30, 0x00000003,
                                             data_ov011_0212ca58, 0x00000003,          data_ov011_0212ca84};

const Ov011Rec_WP data_ov011_0212be40 = {0x00000003, data_ov011_0212cab0};

const Ov011Rec_WP data_ov011_0212be48 = {0x00000003, data_ov011_0212c4b8};

const Ov011Rec_WP data_ov011_0212be50 = {0x00000003, data_ov011_0212c764};

const Ov011Rec_WPWPWP data_ov011_0212be58 = {0x00000003,          data_ov011_0212c5fc, 0x00000003,
                                             data_ov011_0212c740, 0x00000003,          data_ov011_0212c620};

const Ov011Rec_WP data_ov011_0212be70 = {0x00000003, data_ov011_0212c644};

const Ov011Rec_WPWPWP data_ov011_0212be78 = {0x00000003,          data_ov011_0212c494, 0x00000003,
                                             data_ov011_0212c590, 0x00000003,          data_ov011_0212c56c};

const Ov011Rec_WP data_ov011_0212be90 = {0x00000003, data_ov011_0212c5b4};

const Ov011Rec_WPWPWP data_ov011_0212be98 = {0x00000003,          data_ov011_0212c8f0, 0x00000003,
                                             data_ov011_0212c918, 0x00000003,          data_ov011_0212c940};

const Ov011Rec_WP data_ov011_0212beb0 = {0x00000003, data_ov011_0212c968};

const Ov011Rec_WPWPWP data_ov011_0212beb8 = {0x00000003,          data_ov011_0212c470, 0x00000003,
                                             data_ov011_0212c500, 0x00000003,          data_ov011_0212c4dc};

const Ov011Rec_WP data_ov011_0212bed0 = {0x00000003, data_ov011_0212c524};

const Ov011Rec_WPWPWP data_ov011_0212bed8 = {0x00000003,          data_ov011_0212c68c, 0x00000003,
                                             data_ov011_0212c800, 0x00000003,          data_ov011_0212c828};

const Ov011Rec_WP data_ov011_0212bef0 = {0x00000003, data_ov011_0212c850};

const Ov011Rec_WPWPWP data_ov011_0212bef8 = {0x00000003,          data_ov011_0212c668, 0x00000003,
                                             data_ov011_0212c788, 0x00000003,          data_ov011_0212c7b0};

const Ov011Rec_WP data_ov011_0212bf10 = {0x00000003, data_ov011_0212c7d8};

const Ov011Rec_WPWPW data_ov011_0212bf18 = {0x00000003, data_ov011_0212c990, 0x00000003, data_ov011_0212c9b8, 0x00000003};

const Ov011Rec_P data_ov011_0212bf2c = {data_ov011_0212c9e0};

const Ov011Rec_WP data_ov011_0212bf30 = {0x00000003, data_ov011_0212ca08};

const Ov011Rec_WPWPWP data_ov011_0212bf38 = {0x00000003,          data_ov011_0212c5d8, 0x00000003,
                                             data_ov011_0212c6b0, 0x00000003,          data_ov011_0212c6d4};

const Ov011Rec_WP data_ov011_0212bf50 = {0x00000003, data_ov011_0212c6f8};

const Ov011Rec_WPWPWP data_ov011_0212bf58 = {0x00000003,          data_ov011_0212c71c, 0x00000003,
                                             data_ov011_0212c878, 0x00000003,          data_ov011_0212c8a0};

const Ov011Rec_WP data_ov011_0212bf70 = {0x00000003, data_ov011_0212c8c8};

const u16 data_ov011_0212bf78[3] = {4, 4, 4};

const u16 data_ov011_0212bf7e[3] = {448, 128, 112};

const u8 data_ov011_0212bf84[8] = {1, 0, 3, 0, 2, 0, 0, 0};

const u8 data_ov011_0212bf8c[8] = {1, 0, 3, 0, 2, 0, 0, 0};

const u8 data_ov011_0212bf94[8] = {1, 0, 3, 0, 2, 0, 0, 0};

const u8 data_ov011_0212bf9c[8] = {1, 0, 3, 0, 2, 0, 0, 0};

const TaskHandle data_ov011_0212bfa4 = {(const char*)data_ov011_0212cbbc,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_021259d0, 60};

const u8 data_ov011_0212bfb0[16] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0};

const u8 data_ov011_0212bfc0[16] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0};

const u8 data_ov011_0212bfd0[16] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0};

const u16 data_ov011_0212bfe0[10] = {288, 328, 332, 384, 512, 420, 312, 336, 332, 332};

const u16 data_ov011_0212bff4[10] = {7, 4, 4, 4, 4, 4, 4, 4, 4, 4};

const u8 data_ov011_0212c008[24] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0, 1, 0, 3, 0, 2, 0, 2, 0};

const u8 data_ov011_0212c020[32] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0,
                                    1, 0, 3, 0, 2, 0, 2, 0, 1, 0, 3, 0, 2, 0, 3, 0};

const u8 data_ov011_0212c040[32] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0,
                                    1, 0, 3, 0, 2, 0, 2, 0, 1, 0, 3, 0, 2, 0, 3, 0};

const u8 data_ov011_0212c060[48] = {1, 0, 3, 0, 2, 0, 0, 0, 4, 0, 6, 0, 5, 0, 0, 0, 4, 0, 6, 0, 5, 0, 1, 0,
                                    4, 0, 6, 0, 5, 0, 2, 0, 4, 0, 6, 0, 5, 0, 3, 0, 4, 0, 6, 0, 5, 0, 4, 0};

const u8 data_ov011_0212c090[48] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0, 1, 0, 3, 0, 2, 0, 2, 0,
                                    1, 0, 3, 0, 2, 0, 3, 0, 1, 0, 3, 0, 2, 0, 4, 0, 1, 0, 3, 0, 2, 0, 5, 0};

const u8 data_ov011_0212c0c0[88] = {1, 0, 3, 0, 2, 0, 0, 0, 1, 0, 3, 0, 2, 0, 1, 0, 1, 0, 3, 0, 2, 0, 2, 0, 1, 0, 3,  0, 2, 0,
                                    3, 0, 1, 0, 3, 0, 2, 0, 4, 0, 1, 0, 3, 0, 2, 0, 5, 0, 1, 0, 3, 0, 2, 0, 6, 0, 1,  0, 3, 0,
                                    2, 0, 7, 0, 1, 0, 3, 0, 2, 0, 8, 0, 1, 0, 3, 0, 2, 0, 9, 0, 1, 0, 3, 0, 2, 0, 10, 0};

const TaskHandle data_ov011_0212c118 = {(const char*)data_ov011_0212cbe8,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_02125cf8, 596};

const s32 data_ov011_0212c124[3] = {-32768, -65536, 0};

const Ov011Rec_PPW data_ov011_0212c130 = {data_ov011_0212cbfc, func_ov011_021278d4, 0x00000208};

const BtlEnm010RGAim data_ov011_0212c13c[3] = {
    {0x0000, 10},
    {0x0400, 10},
    {0xFC00, 10}
};

const s32 data_ov011_0212c148[4] = {0, 1, 0, 3};

const BtlEnm010RGEntry data_ov011_0212c158 = {
    {(void (*)(void*, s32, s32))func_ov011_0212791c, (void (*)(void*, s32, s32))func_ov011_02127a64,
     (void (*)(void*, s32, s32))func_ov011_02127b98, (void (*)(void*, s32, s32))func_ov011_02127bdc}
};

const s32 data_ov011_0212c168[4] = {1, 2, 0, 3};

const s32 data_ov011_0212c178[5] = {7, 4, 8, 4, 9};

const s32 data_ov011_0212c18c[5] = {2, 4, 1, 2, 0};

const s32 data_ov011_0212c1a0[6] = {2, 1, 5, 4, 2, 0};

const s32 data_ov011_0212c1b8[7] = {0, 2, 1, 4, 3, 5, 9};

const TaskHandle data_ov011_0212c1d4 = {(const char*)data_ov011_0212cc10,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_02127ce0, 108};

const TaskHandle data_ov011_0212c1e0 = {(const char*)data_ov011_0212cc24,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_0212801c, 32};

const s32 data_ov011_0212c1ec[3] = {4096, 3584, 3072};

const TaskHandle data_ov011_0212c1f8 = {(const char*)data_ov011_0212cc38,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_02128348, 180};

const s32 data_ov011_0212c204[3] = {4096, 3277, 2458};

const TaskHandle data_ov011_0212c210 = {(const char*)data_ov011_0212cc54,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_02128758, 184};

const s32 data_ov011_0212c21c[5] = {4096, 3584, 3072, 2560, 2048};

const s32 data_ov011_0212c230[4] = {-344064, 0, -65536, 0};

const TaskHandle data_ov011_0212c240 = {(const char*)data_ov011_0212cc68,
                                        (s32(*)(struct TaskPool*, struct Task*, void*, s32))func_ov011_02129934, 592};

const s32 data_ov011_0212c24c[4] = {-786432, -589824, -393216, -196608};

const s32 data_ov011_0212c25c[6] = {-81920, -294912, -81920, -458752, -344064, -458752};

const s32 data_ov011_0212c274[6] = {196608, -131072, 196608, -458752, -65536, -458752};

const u16 data_ov011_0212c28c[1] = {2366};

const u16 data_ov011_0212c28e[1] = {10};

const u16 data_ov011_0212c290[62] = {1, 0, 6371,  9, 1, 0, 10922, 8, 1, 0, 15109, 7, 1, 0, 17840, 6,
                                     0, 0, 21845, 7, 0, 0, 26396, 8, 0, 0, 30583, 9, 0, 0, 35134, 0,
                                     1, 0, 39139, 1, 1, 0, 43690, 2, 1, 0, 47877, 3, 1, 0, 50608, 4,
                                     0, 0, 54613, 3, 0, 0, 59164, 2, 0, 0, 63351, 1, 0, 0};

const s16 data_ov011_0212c30c[1] = {1200};

const s16 data_ov011_0212c30e[1] = {60};

const char data_ov011_0212c310[8] = {0x00, 0x00, 0x32, 0x00, 0x32, 0x00, 0x00, 0x00};

const char data_ov011_0212c318[8] = {0x00, 0x00, 0x32, 0x00, 0x32, 0x00, 0x00, 0x00};

const char data_ov011_0212c320[8] = {0x00, 0x00, 0x32, 0x00, 0x32, 0x00, 0x00, 0x00};

const char data_ov011_0212c328[8] = {0x00, 0x00, 0x32, 0x00, 0x32, 0x00, 0x00, 0x00};

const s32 data_ov011_0212c330[3] = {4, 7, 2};

const s32 data_ov011_0212c33c[4] = {0, 1, 0, 3};

const s32 data_ov011_0212c34c[4] = {1, 1, 0, 2};

const s32 data_ov011_0212c35c[4] = {30, 40, 50, 60};

const BtlEnm010FnTable data_ov011_0212c36c = {
    {(BtlEnm010Fn)func_ov011_0212b9e4, (BtlEnm010Fn)func_ov011_0212bac8, (BtlEnm010Fn)func_ov011_0212bc84,
     (BtlEnm010Fn)func_ov011_0212bcc8}
};

const s32 data_ov011_0212c37c[5] = {1, 1, 2, 1, 0};

const s32 data_ov011_0212c390[6] = {3, 1, 2, 1, 3, 0};

const s32 data_ov011_0212c3a8[8] = {1, 0, 1, 0, 2, 2, 3, 3};

const s32 data_ov011_0212c3c8[1] = {3};

const u16 data_ov011_0212c3cc[2] = {8192, 0};

const s32 data_ov011_0212c3d0[1] = {819};

const s16 data_ov011_0212c3d4[58] = {10, 0, 0, 0, 0,    0, 0,   0, 0,  0, 5, 0, 8192, 0, 819,  0, 10, 0, 0, 0,
                                     0,  0, 0, 0, 0,    0, 0,   0, 0,  0, 0, 0, 0,    0, 0,    0, 0,  0, 0, 0,
                                     0,  0, 4, 0, 8192, 0, 819, 0, 10, 0, 3, 0, 5462, 0, 1638, 0, 30, 0};

const Ov011Rec_PPW data_ov011_0212c448 = {data_ov011_0212cc8c, func_ov011_0212b99c, 0x00000214};

Ov011Rec_PPPP data_ov011_0212c460 = {&data_ov011_0212bdf8, &data_ov011_0212bde8, &data_ov011_0212be18, &data_ov011_0212be08};

char data_ov011_0212c470[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x4D, 0x6F,
                                0x74, 0x4D, 0x6F, 0x76, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c494[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x4D, 0x6F,
                                0x74, 0x54, 0x75, 0x72, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c4b8[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x45, 0x66,
                                0x66, 0x53, 0x68, 0x6F, 0x74, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c4dc[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D,
                                0x6F, 0x74, 0x4D, 0x6F, 0x76, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c500[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D,
                                0x6F, 0x74, 0x4D, 0x6F, 0x76, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

u8 data_ov011_0212c524[16] = {65, 112, 108, 95, 83, 117, 121, 47, 71, 114, 112, 95, 66, 116, 108, 69};

char data_ov011_0212c534[20] = {0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74,
                                0x4D, 0x6F, 0x76, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c548[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x45, 0x66,
                                0x66, 0x52, 0x61, 0x6E, 0x67, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c56c[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D,
                                0x6F, 0x74, 0x54, 0x75, 0x72, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c590[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D,
                                0x6F, 0x74, 0x54, 0x75, 0x72, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c5b4[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D,
                                0x6F, 0x74, 0x54, 0x75, 0x72, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c5d8[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x4D, 0x6F,
                                0x74, 0x53, 0x77, 0x6F, 0x72, 0x64, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c5fc[36] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F,
                                0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x4D, 0x6F,
                                0x74, 0x4C, 0x61, 0x73, 0x65, 0x72, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c620[36] = "Apl_Suy/Grp_BtlEnm010b_MotLaser.bin";

char data_ov011_0212c644[36] = "Apl_Suy/Grp_BtlEnm010c_MotLaser.bin";

char data_ov011_0212c668[36] = "Apl_Suy/Grp_BtlEnm010_MotBreath.bin";

char data_ov011_0212c68c[36] = "Apl_Suy/Grp_BtlEnm010_MotTattoo.bin";

char data_ov011_0212c6b0[36] = "Apl_Suy/Grp_BtlEnm010a_MotSword.bin";

char data_ov011_0212c6d4[36] = "Apl_Suy/Grp_BtlEnm010b_MotSword.bin";

char data_ov011_0212c6f8[36] = "Apl_Suy/Grp_BtlEnm010c_MotSword.bin";

char data_ov011_0212c71c[36] = "Apl_Suy/Grp_BtlEnm010_MotRushIn.bin";

char data_ov011_0212c740[36] = "Apl_Suy/Grp_BtlEnm010a_MotLaser.bin";

char data_ov011_0212c764[36] = "Apl_Suy/Grp_BtlEnm010_EffTattoo.bin";

char data_ov011_0212c788[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D, 0x6F, 0x74, 0x42, 0x72,
                                0x65, 0x61, 0x74, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c7b0[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D, 0x6F, 0x74, 0x42, 0x72,
                                0x65, 0x61, 0x74, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c7d8[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74, 0x42, 0x72,
                                0x65, 0x61, 0x74, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c800[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D, 0x6F, 0x74, 0x54, 0x61,
                                0x74, 0x74, 0x6F, 0x6F, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c828[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D, 0x6F, 0x74, 0x54, 0x61,
                                0x74, 0x74, 0x6F, 0x6F, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c850[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74, 0x54, 0x61,
                                0x74, 0x74, 0x6F, 0x6F, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c878[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75,
                                0x73, 0x68, 0x49, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c8a0[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75,
                                0x73, 0x68, 0x49, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c8c8[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75,
                                0x73, 0x68, 0x49, 0x6E, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c8f0[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75, 0x73,
                                0x68, 0x4F, 0x75, 0x74, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212c918[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75,
                                0x73, 0x68, 0x4F, 0x75, 0x74, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c940[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75,
                                0x73, 0x68, 0x4F, 0x75, 0x74, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c968[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74, 0x52, 0x75,
                                0x73, 0x68, 0x4F, 0x75, 0x74, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c990[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F, 0x4D, 0x6F, 0x74, 0x4D, 0x6F, 0x76,
                                0x65, 0x52, 0x75, 0x73, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00};

char data_ov011_0212c9b8[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D, 0x6F, 0x74, 0x4D, 0x6F,
                                0x76, 0x65, 0x52, 0x75, 0x73, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212c9e0[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D, 0x6F, 0x74, 0x4D, 0x6F,
                                0x76, 0x65, 0x52, 0x75, 0x73, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212ca08[40] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74,
                                0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74, 0x4D, 0x6F,
                                0x76, 0x65, 0x52, 0x75, 0x73, 0x68, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00};

char data_ov011_0212ca30[40] = "Apl_Suy/Grp_BtlEnm010_MotIdleDamage.bin";

char data_ov011_0212ca58[44] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74, 0x6C,
                                0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x61, 0x5F, 0x4D, 0x6F, 0x74, 0x49, 0x64, 0x6C, 0x65,
                                0x44, 0x61, 0x6D, 0x61, 0x67, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212ca84[44] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74, 0x6C,
                                0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x62, 0x5F, 0x4D, 0x6F, 0x74, 0x49, 0x64, 0x6C, 0x65,
                                0x44, 0x61, 0x6D, 0x61, 0x67, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212cab0[44] = {0x41, 0x70, 0x6C, 0x5F, 0x53, 0x75, 0x79, 0x2F, 0x47, 0x72, 0x70, 0x5F, 0x42, 0x74, 0x6C,
                                0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x63, 0x5F, 0x4D, 0x6F, 0x74, 0x49, 0x64, 0x6C, 0x65,
                                0x44, 0x61, 0x6D, 0x61, 0x67, 0x65, 0x2E, 0x62, 0x69, 0x6E, 0x00, 0x00, 0x00, 0x00};

const void* data_ov011_0212cadc[3] = {data_ov011_0212bf8c, data_ov011_0212c0c0, data_ov011_0212c090};

const void* data_ov011_0212cae8[3] = {&data_ov011_0212bdd8, &data_ov011_0212be50, &data_ov011_0212be48};

const void* data_ov011_0212caf4[10] = {data_ov011_0212c060, data_ov011_0212bf9c, data_ov011_0212c040, data_ov011_0212bfd0,
                                       data_ov011_0212bf94, data_ov011_0212bfb0, data_ov011_0212bf84, data_ov011_0212c008,
                                       data_ov011_0212bfc0, data_ov011_0212c020};

const void* data_ov011_0212cb1c[19] = {&data_ov011_0212be28, &data_ov011_0212beb8, &data_ov011_0212bef8, &data_ov011_0212be78,
                                       &data_ov011_0212bf38, &data_ov011_0212bf58, &data_ov011_0212be98, &data_ov011_0212bf18,
                                       &data_ov011_0212bed8, &data_ov011_0212be58, &data_ov011_0212be28, &data_ov011_0212beb8,
                                       &data_ov011_0212bef8, &data_ov011_0212be78, &data_ov011_0212bf38, &data_ov011_0212bf58,
                                       &data_ov011_0212be98, &data_ov011_0212bf18, &data_ov011_0212bed8};

Ov011Rec_PPPPPPPPPPPPPPPPPPPPP data_ov011_0212cb68 = {
    &data_ov011_0212be58, &data_ov011_0212be28, &data_ov011_0212beb8, &data_ov011_0212bef8, &data_ov011_0212be78,
    &data_ov011_0212bf38, &data_ov011_0212bf58, &data_ov011_0212be98, &data_ov011_0212bf18, &data_ov011_0212bed8,
    &data_ov011_0212be58, &data_ov011_0212be40, &data_ov011_0212bed0, &data_ov011_0212bf10, &data_ov011_0212be90,
    &data_ov011_0212bf50, &data_ov011_0212bf70, &data_ov011_0212beb0, &data_ov011_0212bf30, &data_ov011_0212bef0,
    &data_ov011_0212be70};

char data_ov011_0212cbbc[24] = {0x54, 0x61, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30,
                                0x31, 0x30, 0x5F, 0x41, 0x6E, 0x6D, 0x4D, 0x67, 0x72, 0x00, 0x00, 0x00};

char data_ov011_0212cbd4[20] = {0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F,
                                0x41, 0x6E, 0x6D, 0x4D, 0x67, 0x72, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212cbe8[20] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D,
                                0x30, 0x31, 0x30, 0x5F, 0x4C, 0x73, 0x65, 0x72, 0x00, 0x00};

char data_ov011_0212cbfc[20] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D,
                                0x30, 0x31, 0x30, 0x5F, 0x52, 0x47, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212cc10[20] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D,
                                0x30, 0x31, 0x30, 0x5F, 0x52, 0x6E, 0x67, 0x65, 0x00, 0x00};

char data_ov011_0212cc24[20] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D,
                                0x30, 0x31, 0x30, 0x5F, 0x53, 0x57, 0x61, 0x79, 0x00, 0x00};

char data_ov011_0212cc38[28] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D, 0x30, 0x31, 0x30, 0x5F,
                                0x53, 0x69, 0x6E, 0x67, 0x6C, 0x65, 0x53, 0x68, 0x6F, 0x74, 0x00, 0x00, 0x00, 0x00};

char data_ov011_0212cc54[20] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D,
                                0x30, 0x31, 0x30, 0x5F, 0x53, 0x70, 0x72, 0x6C, 0x00, 0x00};

char data_ov011_0212cc68[20] = {0x54, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E, 0x6D,
                                0x30, 0x31, 0x30, 0x5F, 0x54, 0x61, 0x74, 0x74, 0x00, 0x00};

const void* data_ov011_0212cc7c[4] = {data_ov011_0212c310, data_ov011_0212c328, data_ov011_0212c318, data_ov011_0212c320};

char data_ov011_0212cc8c[20] = {0x54, 0x61, 0x73, 0x6B, 0x5F, 0x42, 0x74, 0x6C, 0x45, 0x6E,
                                0x6D, 0x30, 0x31, 0x30, 0x5F, 0x55, 0x47, 0x00, 0x00, 0x00};

BtlEnm010Bss data_ov011_0212cca0;
