name: Build

on:
  push:
  pull_request:

jobs:
  build:
    container: ghcr.io/yotona/twewy-build:latest

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [usa]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare
        run: |
          mv /extract/* ./extract
          mv ./extract/arm7_bios.bin .

      - name: Build
        run: |
          python tools/configure.py --version ${{ matrix.version }} -w wibo --compiler /mwccarm --no-extract
          ninja

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_report
          path: build/${{ matrix.version }}/report.json